version: '2'
services:
    pru1-postgresql:
        container_name: pru1-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/pru1/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=pru1
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
